modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "ganymede"
displayName = "Ganymede"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "IAFEnvoy"
description = '''Load cloth configs into Jupiter'''

[[mixins]]
config = "ganymede.mixins.json"

[[dependencies.ganymede]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ganymede]]
modId = "minecraft"
type = "required"
